nginx_proxy:
  image: mikesir87/docker-nginx-elb-websocket
  environment:
    LISTEN_ON: 8081
    DESTINATION_HOSTNAME: backend
    DESTINATION_PORT: 80
  ports:
    - "8081:8081"
  links:
    - "app:backend"
app:
  image: nginx 
