nginx_proxy:
  image: mikesir87/docker-nginx-elb-websocket
  environment:
    LISTEN_ON: 81
    LISTEN_ON_TLS: 444 
    DESTINATION_HOSTNAME: backend
    DESTINATION_PORT: 8080
  ports:
    - "81:81"
    - "444:444"
  links:
    - "app:backend"
app:
  image: mikesir87/display-headers 
